
version: "3.8"
services:
  qa-server:
    image: qa-service
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8083:8083"
  db:
    image: postgres:14.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: louisa
      POSTGRES_DATABASE: qa
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: