version: "3.7"
services:
  db:
    image: postgres
    environment:
      PGUSER='louisa'
      PGDATABASE='qa'
      PGPASSWORD='password'
    volumes:
      - ./pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'
app:
  image: web
    depends_on:
      - db
    ports:
      - "8080:8080"