
version: "3.8"

services:
  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    # build:
    #   context: .
    #   dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    environment:
      NRIA_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NRIA_DISPLAY_NAME: ${NEW_RELIC_APP_NAME}
    network_mode: host
    # pid: host
    # privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  qa-server:
    image: laweeza/qa-service:latest
    container_name: qa-server
    restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
      NODE_ENV: development
  db:
    image: postgres:14.0
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    external: false