version: "3.1"
services:
  postgresql:
    image: postgres
    environment:
      PGUSER:'louisa'
      PGDATABASE:'qa'
      PGPASSWORD:'password'
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
# app:
#   image: web
#     depends_on:
#       - db
#     ports:
#       - "8080:8080"