
version: "3.8"

  k6:
    image: loadimpact/k6:latest
    entrypoint: /bin/sh
    user: root
    networks:
      - k6
    ports:
      - "6565:6565"
    volumes:
      - ./scripts:/scripts
  qa-server:
    image: qa-service
    working_dir: /QA-Service/server
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8083:8083"
  db:
    image: postgres:14.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: louisa
      POSTGRES_DATABASE: qa
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: