# Manage multi-container docker applications. Instance of an image
version: "3.8"
services:

  #Server
  server:
    image: node:14.18.1
    build: .
    command: "npm run dev"
    depends_on:
      db:
          condition: service_healthy
    ports:
      - "8083:8083"

  # Spins up an instance of PostgreSQL using image from Docker Hub
  db:
    image: "postgres:13"
    container_name: "my_db"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgreql/data
#
