version: "3.1"
services:
  db:
    image: "postgres:13"
    container_name: "my_db"
    environment:
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
