# Manage multi-container docker applications
version: "3.8"
services:
  #Database
  db:
    image: postgres:14.0
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: louisa
      POSTGRES_DATABASE: qa
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
      volumes:
        data:
          driver: local
    expose:
      - "5432"
    ports:
      - "5432:5432"

  #Server
  qa-server:
    container_name: qa-service
    restart: always
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432"]
