# Manage multi-container docker applications
version: "3.8"
services:
  #Database
  db:
    image: "postgres:13"
    restart: always
    environment:
      POSTGRES_USER: louisa
      POSTGRES_DATABASE: qa
      POSTGRES_PASSWORD: password
    volumes:
      - ./pg-data:/var/lib/postgreql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
  #Server
  web:
    image: qa-service-app
    network_mode: host
    depends_on:
      db:
          condition: service_healthy
    ports:
      - '8083:8083'
    command: ["./wait-for-it.sh", "db:5432"]
